### PR TITLE
Rearrange menus

### PR DESCRIPTION
**Pull request by humdingerb**
* Rename "Edit" menu to "Station", as all commands are connected to the
  stations and not all have to do with editing.
* Rename "Remove" to "Remove station". Looks nicer and is consistent with
  "Check station".
* Add shortcut 'V' to "Paste Shoutcast URL" as that's the standard for
  pasting.
* Move "Allow parallel playback" to "App" as it's a setting for the app.
* Add an actual menu item to "Find stations..." under menu "Search" as
  menus without items creep me out.
* Adjust catkeys.

### CODE REVIEW

**Comment by humdingerb** [comment]
@jsteinaker: are you currently workingon something StreamRadio related? I'm asking, because I'd like to adjust the coding style of about every file. That would disrupt all WIP quite a bit...

**Comment by jsteinaker** [comment]
Please go ahead. Nothing at the moment. I'd like to introduce record
capabilities to StreamRadio but I'm far away from that, I seriously need to
take a look at how the Media Kit works.

Thanks for asking and for your job.

**Comment by humdingerb** [comment]
Alright! Tomorrow then... :)

**Comment by Vidrep** [comment]
All of your suggestions in the open tickets sound good. Consistency in the appearance and functions Haiku apps is nice, rather than being a free for all like Linux.

**Pull request merged**
